'use strict';
const $=s=>document.querySelector(s), E=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const TOKEN_KEY='english-lab-token-v1';
let token=localStorage.getItem(TOKEN_KEY)||'', view='new', current=null, problemImgs=[], workImgs=[];
const DB_NAME='english-csat-lab-db', SESSION_STORE='sessions', BANK_STORE='bank';

const TYPES=[
'듣기','목적','심경·분위기','주장','요지','주제','제목','함축 의미','내용 일치/불일치','도표·실용문',
'어법','어휘','빈칸 추론','무관한 문장','글의 순서','문장 삽입','요약문','장문 독해','기타'
];
const SKILLS={
sentence_structure:'문장 구조 파악', vocabulary:'어휘·표현', reference:'지시·대명사 추적',
logic:'논리 흐름', paraphrase:'바꿔쓰기 인식', inference:'추론', evidence:'근거 위치 찾기',
choice_elimination:'선지 제거', question_strategy:'유형별 접근', time_control:'시간 운영'
};
const STRATEGIES={
'목적':'첫 문단의 상황과 요청/행동 동사를 우선 확인 → 글쓴이와 수신자의 관계 → 세부 정보는 검증용.',
'심경·분위기':'사건 자체보다 감정 변화를 만드는 평가어·행동·상황 전환을 추적. 초반과 후반 감정이 달라지는지 확인.',
'주장':'필자의 당위·제안·비판을 나타내는 should, need, must, important류와 마지막 정리 문장을 중심으로 판단.',
'요지':'세부 사례를 묶는 상위 문장을 찾고, “그래서 필자가 결국 말하려는 한 문장”으로 압축.',
'주제':'반복되는 핵심 대상 + 필자의 핵심 관점을 명사구로 압축. 지나치게 구체적인 사례 선지 배제.',
'제목':'주제보다 한 단계 표현적. 글 전체를 포괄하되 핵심 대비·역설·관계를 담는지 확인.',
'함축 의미':'밑줄 표현의 사전적 뜻이 아니라 앞뒤 문맥에서 그 표현이 대신하는 주장/관계를 풀어쓴다.',
'어법':'문장 전체 뜻보다 구조 먼저. 주어-동사, 수식 범위, 병렬, 관계절, 준동사, 수일치 순서로 점검.',
'어휘':'해당 단어 주변 한 문장만 보지 말고 문단의 논리 방향(긍/부정, 증가/감소, 원인/결과)을 먼저 잡는다.',
'빈칸 추론':'빈칸을 채우려 하지 말고 빈칸이 담당하는 역할부터 판정 → 앞뒤 핵심문장 압축 → 선지를 문맥에 재삽입.',
'무관한 문장':'각 문장을 한 줄로 요약해 공통 주제의 연결 고리를 추적. 앞뒤 모두와 의미 연결이 끊기는 문장을 찾는다.',
'글의 순서':'주어진 문단의 핵심 화제를 잡고, 대명사/지시어/관사/연결어/예시-일반 관계를 이용해 문단 간 필연적 연결을 찾는다.',
'문장 삽입':'삽입문 안의 지시어·대명사·연결어가 요구하는 선행 정보를 찾고, 삽입 전후 문장의 연결이 동시에 자연스러운 위치를 고른다.',
'요약문':'원문의 핵심 관계를 두 축으로 압축한 뒤 빈칸 A/B의 품사·긍부정·인과 방향을 맞춘다.',
'장문 독해':'첫 읽기에서 전체 상황과 인물/논지 구조를 잡고, 문항별로 필요한 부분만 재탐색. 문항 순서에 끌려 지문을 반복 정독하지 않는다.',
'내용 일치/불일치':'선지의 고유명사·숫자·조건어를 검색 키워드로 삼아 지문에서 직접 대조. 추론하지 말고 사실 대응.',
'도표·실용문':'조건·숫자·예외를 체크리스트처럼 대조. 해석보다 정확한 정보 탐색이 핵심.',
'듣기':'선지를 먼저 훑어 필요한 정보 범주를 예측하고, 숫자·장소·의도·관계 등 목표 정보에 집중.'
};

function toast(s){const t=$('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function db(){return new Promise((res,rej)=>{const q=indexedDB.open(DB_NAME,1);q.onupgradeneeded=()=>{const d=q.result;if(!d.objectStoreNames.contains(SESSION_STORE))d.createObjectStore(SESSION_STORE,{keyPath:'id'});if(!d.objectStoreNames.contains(BANK_STORE))d.createObjectStore(BANK_STORE,{keyPath:'id'})};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function put(store,obj){const d=await db();return new Promise((res,rej)=>{const tx=d.transaction(store,'readwrite');tx.objectStore(store).put(obj);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
async function getAll(store){const d=await db();return new Promise((res,rej)=>{const q=d.transaction(store).objectStore(store).getAll();q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function getOne(store,id){const d=await db();return new Promise((res,rej)=>{const q=d.transaction(store).objectStore(store).get(id);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function del(store,id){const d=await db();return new Promise((res,rej)=>{const tx=d.transaction(store,'readwrite');tx.objectStore(store).delete(id);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
async function sessions(){const a=await getAll(SESSION_STORE);return a.sort((x,y)=>new Date(y.updatedAt)-new Date(x.updatedAt))}
function uid(){return crypto.randomUUID()}
function fmt(d){return new Date(d).toLocaleString('ko-KR')}
async function compress(file){return new Promise((res,rej)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{const max=1800,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);res(c.toDataURL('image/jpeg',.84))};img.onerror=rej;img.src=url})}
async function filesToData(files){const out=[];for(const f of files){if(f.type.startsWith('image/'))out.push(await compress(f))}return out}
function imgs(a){return '<div class="preview">'+(a||[]).map(x=>'<img src="'+x+'">').join('')+'</div>'}
function opt(arr,sel=''){return arr.map(x=>'<option '+(x===sel?'selected':'')+'>'+E(x)+'</option>').join('')}
function setNav(){const n=$('#nav');n.classList.toggle('hidden',!token);n.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.view===view))}
async function health(){try{return await (await fetch('/api/health')).json()}catch{return {ok:false}}}
function loginView(msg=''){return '<div class="login panel"><div class="brand">수능 영어 분석 연구실</div><p class="muted">교사용 개인 프로그램입니다.</p>'+(msg?'<p class="bad">'+E(msg)+'</p>':'')+'<label>접속 암호</label><input id="pw" type="password"><div class="actions"><button id="login" class="btn primary">들어가기</button></div></div>'}
async function login(){const password=$('#pw').value;if(!password)return;const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});const j=await r.json().catch(()=>({}));if(!r.ok){$('#app').innerHTML=loginView(j.error||'암호를 확인하세요.');return}token=j.token;localStorage.setItem(TOKEN_KEY,token);render()}

function newView(){return '<h1>새 문항 분석</h1><section class="panel"><div class="grid4"><div><label>시험</label><select id="exam"><option>수능</option><option>6월 모의평가</option><option>9월 모의평가</option><option>교육청 모의고사</option><option>기타</option></select></div><div><label>학년도/연도</label><input id="year" type="text" placeholder="2027학년도"></div><div><label>문항 번호</label><input id="number" type="number" min="1" max="45" placeholder="31"></div><div><label>예상 유형</label><select id="type"><option>AI 자동 판별</option>'+opt(TYPES)+'</select></div></div><div class="grid"><div><label>내가 고른 답 (선택)</label><input id="chosen" type="text" placeholder="예: ③"></div><div><label>풀이 시간 (초, 선택)</label><input id="seconds" type="number" min="0" placeholder="95"></div></div><label>문제/지문 캡처</label><input id="problemFiles" type="file" accept="image/*" multiple>'+imgs(problemImgs)+'<div class="divider"></div><h2>내 해석·풀이 생각</h2><label>해석/필기 캡처</label><input id="workFiles" type="file" accept="image/*" multiple>'+imgs(workImgs)+'<label>전체 흐름 또는 풀이 생각</label><textarea id="thought" placeholder="예: 1문단은 기존 통념, 2문단에서 반박. 빈칸은 결국 새로운 관점의 장점을 말하는 것 같음. ②와 ④ 사이에서 고민함."></textarea><label>직접 적은 해석/해석이 불안한 문장 (선택)</label><textarea id="translation" placeholder="내 해석을 텍스트로 적어도 됩니다. 캡처와 함께 보내도 됩니다."></textarea><div class="actions"><button id="analyze" class="btn primary">정밀 분석</button></div><p class="small">문항 유형, 지문 흐름, 해석 오류, 중요 구문·어휘, 선지 판단, 유형별 접근법, 반복 습관까지 한 번에 분석해 기록합니다.</p></section>'}

function scoreRows(scores={}){return Object.entries(SKILLS).map(([k,n])=>{const v=Math.max(0,Math.min(5,Number(scores[k]||0)));return '<div class="score"><span>'+n+'</span><div class="bar"><i style="width:'+(v/5*100)+'%"></i></div><b>'+v.toFixed(1)+'</b></div>'}).join('')}
function analysisHtml(a){if(!a)return '';const tr=(a.translation_feedback||[]).map(x=>'<div class="translation"><b>'+E(x.source||'문장')+'</b><div class="small">내 해석/문제점</div><div>'+E(x.issue||'')+'</div><div class="small">권장 해석</div><div>'+E(x.better_translation||'')+'</div><div class="small">'+E(x.reason||'')+'</div></div>').join('');
const voc=(a.vocabulary||[]).map(v=>'<div class="vocab"><b>'+E(v.expression)+'</b> <span class="badge">'+E(v.level||'')+'</span><div>'+E(v.meaning||'')+'</div><div class="small">'+E(v.usage||'')+(v.synonyms?.length?' · 유의어: '+E(v.synonyms.join(', ')):'')+'</div></div>').join('');
const traps=(a.choice_analysis?.traps||[]).map(x=>'<div class="trap"><b>'+E(x.choice||'선지')+'</b> '+E(x.reason||'')+'</div>').join('');
const habits=(a.overall_feedback?.habits||[]).map(h=>'<div class="trap"><b>'+E(h.name)+'</b><div>'+E(h.evidence||'')+'</div><div class="small">교정: '+E(h.correction||'')+'</div></div>').join('');
return '<section class="panel"><div class="row spread"><div><h2>문항 진단</h2><span class="badge">'+E(a.question_type||'유형')+'</span></div><div><b>정답 판단: '+E(a.answer||'')+'</b></div></div><h3>이 문항의 핵심 접근</h3><div class="feedback">'+E(a.approach||'')+'</div><h3>지문 전체 흐름</h3><div class="flow">'+E(a.passage_flow||'')+'</div><h3>정답 근거 위치</h3><div class="quote">'+E(a.evidence||'')+'</div><h3>선지 판단</h3><div class="feedback">'+E(a.choice_analysis?.best_reason||'')+'</div>'+traps+'</section>'+
'<section class="panel"><h2>해석·구문 피드백</h2>'+(tr||'<p class="muted">뚜렷한 해석 오류가 확인되지 않았거나 해석 자료가 충분하지 않습니다.</p>')+'<h3>중요 구문</h3><div class="feedback">'+E((a.syntax||[]).map(x=>'• '+x).join('\n'))+'</div></section>'+
'<section class="panel"><h2>중요 어휘·표현</h2>'+voc+'</section>'+
'<section class="panel"><h2>수능 영어 역량 피드백</h2>'+scoreRows(a.overall_feedback?.scores||{})+'<h3>현재 가장 큰 병목</h3><div class="feedback">'+E(a.overall_feedback?.bottleneck||'')+'</div><h3>고쳐야 할 습관</h3>'+(habits||'<p class="muted">이번 문항에서 뚜렷한 습관 문제는 확인되지 않았습니다.</p>')+'<h3>다음 문제에서 바로 적용할 행동</h3><div class="feedback">'+E(a.overall_feedback?.next_action||'')+'</div></section>'}

async function historySummary(){const ss=await sessions();return ss.slice(0,15).map(s=>{const a=s.analysis;return {source:s.source,type:a?.question_type||s.type,number:s.number,translationIssues:(a?.translation_feedback||[]).map(x=>x.reason),scores:a?.overall_feedback?.scores||{},habits:(a?.overall_feedback?.habits||[]).map(h=>h.name),bottleneck:a?.overall_feedback?.bottleneck||''}})}
async function callAnalyze(s){const r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify({...s,history:await historySummary()})});const j=await r.json().catch(()=>({}));if(r.status===401){token='';localStorage.removeItem(TOKEN_KEY);render();throw new Error('다시 로그인해주세요.')}if(!r.ok)throw new Error(j.error||'분석 실패');return j.analysis}
async function saveBankFrom(a,s){for(const v of (a.vocabulary||[])){const key=(v.expression||'').trim().toLowerCase();if(!key)continue;const all=await getAll(BANK_STORE);const old=all.find(x=>x.key===key);const obj=old||{id:uid(),key,expression:v.expression,meaning:v.meaning,usage:v.usage,synonyms:v.synonyms||[],count:0,examples:[],createdAt:new Date().toISOString()};obj.count=(obj.count||0)+1;obj.updatedAt=new Date().toISOString();obj.examples=[...(obj.examples||[]),s.source].slice(-8);await put(BANK_STORE,obj)}}
async function analyzeNew(){if(!problemImgs.length)return toast('문제/지문 캡처를 올려주세요.');const now=new Date().toISOString(),s={id:uid(),source:[$('#year').value.trim(),$('#exam').value,$('#number').value?$('#number').value+'번':''].filter(Boolean).join(' '),exam:$('#exam').value,year:$('#year').value.trim(),number:$('#number').value,type:$('#type').value,chosen:$('#chosen').value.trim(),seconds:Number($('#seconds').value||0),problemImages:problemImgs,workImages:workImgs,thought:$('#thought').value.trim(),translation:$('#translation').value.trim(),createdAt:now,updatedAt:now};$('#app').innerHTML='<section class="panel"><h2>분석 중…</h2><p class="muted">지문 구조, 해석, 문항 유형, 선지 근거와 어휘·표현을 함께 보고 있습니다.</p></section>';try{s.analysis=await callAnalyze(s);await put(SESSION_STORE,s);await saveBankFrom(s.analysis,s);current=s;problemImgs=[];workImgs=[];view='session';render()}catch(e){toast(e.message);view='new';render()}}

async function sessionView(){const s=current;if(!s){view='history';return historyView()}return '<div class="row spread"><div><h1>'+E(s.source||'문항 기록')+'</h1><div class="muted">'+E(s.analysis?.question_type||s.type)+' · '+fmt(s.updatedAt)+(s.seconds?' · '+s.seconds+'초':'')+'</div></div><button id="backHistory" class="btn">기록으로</button></div><section class="panel"><h2>원문</h2>'+imgs(s.problemImages)+'<h2>내 해석·풀이</h2>'+imgs(s.workImages)+'<div class="feedback">'+E(s.thought||'')+(s.translation?'\n\n[내 해석]\n'+E(s.translation):'')+'</div></section>'+analysisHtml(s.analysis)}
async function historyView(){const ss=await sessions();return '<h1>풀이 기록</h1><section class="panel">'+(ss.length?ss.map(s=>'<div class="item"><div class="row spread"><div><b>'+E(s.source||'문항')+'</b> <span class="badge">'+E(s.analysis?.question_type||s.type)+'</span><div class="small">'+fmt(s.updatedAt)+(s.chosen?' · 내 답 '+E(s.chosen):'')+(s.seconds?' · '+s.seconds+'초':'')+'</div><div class="small">병목: '+E(s.analysis?.overall_feedback?.bottleneck||'')+'</div></div><div class="row"><button class="btn" data-open="'+s.id+'">열기</button><button class="btn danger" data-del="'+s.id+'">삭제</button></div></div></div>').join(''):'아직 분석 기록이 없습니다.')+'</section>'}

function mean(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:0}
async function dashboardView(){const ss=await sessions(),recent=ss.slice(0,20),aa=recent.map(s=>s.analysis).filter(Boolean),avg={};Object.keys(SKILLS).forEach(k=>avg[k]=mean(aa.map(a=>Number(a.overall_feedback?.scores?.[k]||0))));const habits={},types={};aa.forEach(a=>{types[a.question_type]=(types[a.question_type]||0)+1;(a.overall_feedback?.habits||[]).forEach(h=>habits[h.name]=(habits[h.name]||0)+1)});const topHabits=Object.entries(habits).sort((a,b)=>b[1]-a[1]).slice(0,6),topTypes=Object.entries(types).sort((a,b)=>b[1]-a[1]).slice(0,6);return '<h1>학습 현황</h1><section class="panel"><div class="grid3"><div><div class="small">누적 분석 문항</div><div class="kpi">'+ss.length+'</div></div><div><div class="small">최근 20문항 평균</div><div class="kpi">'+mean(Object.values(avg)).toFixed(1)+'/5</div></div><div><div class="small">가장 많이 분석한 유형</div><div class="kpi" style="font-size:20px">'+E(topTypes[0]?.[0]||'기록 필요')+'</div></div></div></section><section class="panel"><h2>최근 20문항 역량</h2>'+scoreRows(avg)+'</section><section class="panel"><div class="grid"><div><h2>반복되는 습관</h2>'+(topHabits.length?topHabits.map(([n,c])=>'<div class="trap"><b>'+E(n)+'</b> · '+c+'회</div>').join(''):'<p class="muted">기록이 더 필요합니다.</p>')+'</div><div><h2>유형별 분석량</h2>'+(topTypes.length?topTypes.map(([n,c])=>'<div class="item"><b>'+E(n)+'</b> '+c+'문항</div>').join(''):'<p class="muted">기록이 더 필요합니다.</p>')+'</div></div></section>'}

async function bankView(){const b=(await getAll(BANK_STORE)).sort((x,y)=>(y.count||0)-(x.count||0));return '<h1>어휘·표현 누적</h1><section class="panel"><p class="muted">분석에서 중요하다고 판정된 어휘와 표현을 자동으로 모읍니다. 반복 출현 횟수가 높은 표현부터 표시합니다.</p>'+(b.length?'<table class="table"><thead><tr><th>표현</th><th>뜻/용법</th><th>횟수</th><th>최근 출처</th></tr></thead><tbody>'+b.map(x=>'<tr><td><b>'+E(x.expression)+'</b></td><td>'+E(x.meaning||'')+'<div class="small">'+E(x.usage||'')+'</div></td><td>'+Number(x.count||0)+'</td><td class="small">'+E((x.examples||[]).slice(-3).join(' / '))+'</td></tr>').join('')+'</tbody></table>':'아직 저장된 표현이 없습니다.')+'</section>'}
function strategiesView(){return '<h1>유형별 접근법</h1><section class="panel"><p class="lead">수능 영어 읽기 문항은 유형별로 “처음 어디를 보고, 어떤 단서를 모으고, 어떻게 선지를 지울지”가 다릅니다. 아래 원칙은 분석 결과에도 함께 반영됩니다.</p>'+Object.entries(STRATEGIES).map(([k,v])=>'<div class="strategy"><b>'+E(k)+'</b><div>'+E(v)+'</div></div>').join('')+'</section>'}
async function settingsView(){const h=await health();return '<h1>설정</h1><section class="panel"><h2>AI 연결</h2><p>'+(h.aiConfigured?'<b class="good">연결됨</b>':'<b class="bad">연결 안 됨</b>')+'</p><p class="small">모델: '+E(h.model||'-')+'</p></section><section class="panel"><h2>백업</h2><div class="actions"><button id="export" class="btn">전체 기록 내보내기</button><label class="btn">기록 불러오기<input id="import" class="hidden" type="file" accept="application/json"></label><button id="logout" class="btn danger">로그아웃</button></div></section>'}
async function exportAll(){const ss=await sessions(),b=await getAll(BANK_STORE),blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),sessions:ss,bank:b},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='english-csat-lab-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
async function importAll(file){const j=JSON.parse(await file.text());for(const s of (j.sessions||[]))await put(SESSION_STORE,s);for(const b of (j.bank||[]))await put(BANK_STORE,b);toast('기록을 불러왔습니다.');view='history';render()}
async function render(){setNav();if(!token){$('#app').innerHTML=loginView();return}let html='';if(view==='new')html=newView();else if(view==='history')html=await historyView();else if(view==='dashboard')html=await dashboardView();else if(view==='bank')html=await bankView();else if(view==='strategies')html=strategiesView();else if(view==='settings')html=await settingsView();else if(view==='session')html=await sessionView();$('#app').innerHTML=html}
document.addEventListener('change',async e=>{if(e.target.id==='problemFiles'){problemImgs=await filesToData(e.target.files);render()}if(e.target.id==='workFiles'){workImgs=await filesToData(e.target.files);render()}if(e.target.id==='import'&&e.target.files[0]){try{await importAll(e.target.files[0])}catch{toast('파일을 읽지 못했습니다.')}}});
document.addEventListener('click',async e=>{const t=e.target.closest('button');if(!t)return;if(t.dataset.view){view=t.dataset.view;current=null;render();return}if(t.id==='login')return login();if(t.id==='analyze')return analyzeNew();if(t.id==='backHistory'){view='history';current=null;return render()}if(t.dataset.open){current=await getOne(SESSION_STORE,t.dataset.open);view='session';return render()}if(t.dataset.del&&confirm('이 기록을 삭제할까요?')){await del(SESSION_STORE,t.dataset.del);return render()}if(t.id==='export')return exportAll();if(t.id==='logout'){token='';localStorage.removeItem(TOKEN_KEY);return render()}});
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.id==='pw')login()});
render();