'use strict';
const $=s=>document.querySelector(s), E=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const API_TOKEN_KEY='killer-lab-token-v1';
let token=localStorage.getItem(API_TOKEN_KEY)||'';
let view='new', current=null, pendingProblem=[], pendingAttempt=[];
const SKILLS={condition_reading:'조건 해석',concept_selection:'개념 선택',condition_connection:'조건 연결',intermediate_goal:'중간 목표 설정',representation:'표현 전환',execution:'계산·전개',verification:'검산·오류 탐지',transfer:'전이·일반화'};
const DB_NAME='killer-lab-db', STORE='sessions';
function toast(s){const t=$('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function openDb(){return new Promise((res,rej)=>{const q=indexedDB.open(DB_NAME,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains(STORE))q.result.createObjectStore(STORE,{keyPath:'id'})};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function putSession(s){const db=await openDb();return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(s);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
async function allSessions(){const db=await openDb();return new Promise((res,rej)=>{const q=db.transaction(STORE).objectStore(STORE).getAll();q.onsuccess=()=>res(q.result.sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt)));q.onerror=()=>rej(q.error)})}
async function getSession(id){const db=await openDb();return new Promise((res,rej)=>{const q=db.transaction(STORE).objectStore(STORE).get(id);q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
async function delSession(id){const db=await openDb();return new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(id);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
function uid(){return crypto.randomUUID()}
function fmt(d){return new Date(d).toLocaleString('ko-KR')}
async function compress(file){return new Promise((res,rej)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);res(c.toDataURL('image/jpeg',.82))};img.onerror=rej;img.src=url})}
async function filesToData(files){const out=[];for(const f of files){if(!f.type.startsWith('image/'))continue;out.push(await compress(f))}return out}
function imgs(list){return '<div class="preview">'+(list||[]).map(x=>'<img src="'+x+'">').join('')+'</div>'}
function setNav(){const n=$('#nav');n.classList.toggle('hidden',!token);n.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.view===view))}
async function health(){try{const r=await fetch('/api/health');return await r.json()}catch{return {ok:false}}}
function loginView(msg=''){return '<div class="login panel"><div class="brand">3·4점 사고훈련 연구실</div><p class="muted">개인용 프로그램입니다. 접속 암호를 입력하세요.</p>'+(msg?'<p class="bad">'+E(msg)+'</p>':'')+'<label>접속 암호</label><input id="pw" type="password" autocomplete="current-password"><div class="actions"><button class="btn primary" id="login">들어가기</button></div></div>'}
async function doLogin(){const password=$('#pw').value;if(!password)return;const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});const j=await r.json().catch(()=>({}));if(!r.ok){$('#app').innerHTML=loginView(j.error||'암호를 확인하세요.');return}token=j.token;localStorage.setItem(API_TOKEN_KEY,token);setNav();render()}
function newView(){return '<h1>새 문제 분석</h1><section class="panel"><div class="grid"><div><label>문제 이름 / 출처</label><input id="title" type="text" placeholder="예: 2026 9월 모의 수학 22번"></div><div><label>단원 / 태그</label><input id="tags" type="text" placeholder="미분, 함수 추론, 정수 조건"></div></div><label>문제 이미지</label><input id="problemFiles" type="file" accept="image/*" multiple>'+imgs(pendingProblem)+'<div class="divider"></div><h2>현재까지의 풀이</h2><label>풀이 사진</label><input id="attemptFiles" type="file" accept="image/*" multiple>'+imgs(pendingAttempt)+'<label>내 생각 / 어디서 막혔는지</label><textarea id="note" placeholder="예: 여기까지는 했는데 f(a)=f(b)를 어디에 써야 할지 모르겠음"></textarea><div class="actions"><button class="btn primary" id="analyzeNew">사고과정 진단</button></div><p class="small">원칙: 완성 풀이·정답을 바로 주지 않고, 현재 사고가 끊긴 지점과 다음 질문만 단계적으로 제시합니다.</p></section>'}
function skillRows(scores={}){return Object.entries(SKILLS).map(([k,n])=>{const v=Math.max(0,Math.min(5,Number(scores[k]??0)));return '<div class="score"><span>'+n+'</span><div class="bar"><i style="width:'+(v/5*100)+'%"></i></div><b>'+v.toFixed(1)+'</b></div>'}).join('')}
function analysisHtml(a){if(!a)return '';const cm=(a.condition_map||[]).map(x=>'<div class="condition"><div class="row spread"><b>'+E(x.condition)+'</b><span class="state">'+E(x.state)+'</span></div><div class="small">'+E(x.meaning||'')+'</div></div>').join('');const habits=(a.killer_feedback?.habits||[]).map(h=>'<div class="habit"><b>'+E(h.name)+'</b><div>'+E(h.evidence||'')+'</div><div class="small">영향: '+E(h.impact||'')+' · 교정: '+E(h.correction||'')+'</div></div>').join('');return '<section class="panel"><h2>이번 사고과정 진단</h2><h3>지금까지 잘한 부분</h3><div class="feedback">'+E((a.correct_work||[]).map(x=>'• '+x).join('\n')||'아직 명확히 확인된 부분 없음')+'</div><h3>처음 막힌 지점</h3><div class="feedback">'+E(a.first_block||'')+'</div><h3>조건 사용 지도</h3>'+cm+'<h3>다음에 스스로 답할 질문</h3><div class="question">'+E(a.next_question||'')+'</div><h3>최소 힌트</h3><div class="feedback">'+E(a.hint||'')+'</div></section><section class="panel"><h2>킬러 역량 점검</h2><div class="stage">'+E(a.killer_feedback?.stage||'')+'</div><p>'+E(a.killer_feedback?.readiness_comment||'')+'</p>'+skillRows(a.killer_feedback?.scores||{})+'<h3>현재 병목</h3><div class="feedback">'+E(a.killer_feedback?.bottleneck||'')+'</div><h3>고쳐야 할 습관</h3>'+(habits||'<p class="muted">이번 풀이에서 뚜렷한 습관 문제는 아직 확인되지 않았습니다.</p>')+'<h3>다음 목표</h3><div class="feedback">'+E(a.killer_feedback?.next_milestone||'')+'</div></section>'}
async function historySummary(){const ss=await allSessions();return ss.slice(0,10).map(s=>{const a=s.analyses?.at(-1);return {date:s.updatedAt,title:s.title,tags:s.tags,first_block:a?.first_block||'',scores:a?.killer_feedback?.scores||{},habits:(a?.killer_feedback?.habits||[]).map(h=>h.name)}})}
async function callAnalyze(session,attempt,hintLevel){const body={sessionId:session.id,title:session.title,tags:session.tags,problemImages:session.problemImages,solutionImages:attempt.images,note:attempt.note,hintLevel,previousAnalyses:session.analyses||[],history:await historySummary()};const r=await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(r.status===401){token='';localStorage.removeItem(API_TOKEN_KEY);render();throw new Error('다시 로그인해주세요.')}if(!r.ok)throw new Error(j.error||'AI 진단 실패');return j.analysis}
async function analyzeNew(){const title=$('#title').value.trim()||'이름 없는 문제',tags=$('#tags').value.trim(),note=$('#note').value.trim();if(!pendingProblem.length)return toast('문제 이미지를 먼저 올려주세요.');if(!pendingAttempt.length&&!note)return toast('풀이 사진이나 현재 생각을 남겨주세요.');const now=new Date().toISOString();const s={id:uid(),title,tags,problemImages:pendingProblem,createdAt:now,updatedAt:now,attempts:[],analyses:[]};const at={id:uid(),at:now,images:pendingAttempt,note,hintLevel:0};s.attempts.push(at);await putSession(s);current=s;view='session';setNav();$('#app').innerHTML='<section class="panel"><h2>분석 중…</h2><p class="muted">문제 조건과 현재 풀이를 비교하고 있습니다.</p></section>';try{const a=await callAnalyze(s,at,0);s.analyses.push({...a,attemptId:at.id,at:new Date().toISOString()});s.updatedAt=new Date().toISOString();await putSession(s);pendingProblem=[];pendingAttempt=[];render()}catch(e){toast(e.message);view='new';render()}}
async function sessionView(){const s=current;if(!s)return historyView();const a=s.analyses?.at(-1),lastAttempt=s.attempts?.at(-1);return '<div class="row spread"><div><h1>'+E(s.title)+'</h1><div class="muted">'+E(s.tags||'태그 없음')+' · '+fmt(s.updatedAt)+'</div></div><button class="btn" id="backHistory">기록으로</button></div><section class="panel"><h2>문제</h2>'+imgs(s.problemImages)+'<h2>최근 풀이</h2>'+imgs(lastAttempt?.images||[])+'<div class="feedback">'+E(lastAttempt?.note||'')+'</div></section>'+analysisHtml(a)+'<section class="panel"><h2>다시 시도</h2><p class="muted">새 풀이를 만든 뒤 다시 올리면 이전 분석과 비교해서 다음 막힘을 찾습니다.</p><label>새 풀이 사진</label><input id="retryFiles" type="file" accept="image/*" multiple><div id="retryPreview"></div><label>이번에 새로 시도한 생각</label><textarea id="retryNote"></textarea><div class="actions"><button class="btn primary" id="retryAnalyze">새 풀이 분석</button><button class="btn" id="strongerHint">같은 풀이에서 힌트 1단계 올리기</button></div><p class="small">힌트 단계는 최대 4단계이며, 끝까지 완성 풀이를 자동 공개하지 않습니다.</p></section>'}
async function retryAnalyze(stronger=false){const s=current,last=s.attempts.at(-1);let images=stronger?last.images:pendingAttempt,note=stronger?last.note:$('#retryNote').value.trim();if(!stronger&&!images.length&&!note)return toast('새 풀이 사진이나 생각을 남겨주세요.');const level=stronger?Math.min(4,(last.hintLevel||0)+1):0;const at=stronger?{...last,id:uid(),at:new Date().toISOString(),hintLevel:level}:{id:uid(),at:new Date().toISOString(),images,note,hintLevel:0};s.attempts.push(at);s.updatedAt=new Date().toISOString();await putSession(s);$('#app').innerHTML='<section class="panel"><h2>다시 분석 중…</h2></section>';try{const a=await callAnalyze(s,at,level);s.analyses.push({...a,attemptId:at.id,at:new Date().toISOString()});s.updatedAt=new Date().toISOString();await putSession(s);pendingAttempt=[];render()}catch(e){toast(e.message);render()}}
async function historyView(){const ss=await allSessions();return '<h1>전체 풀이 기록</h1><section class="panel">'+(ss.length?ss.map(s=>{const a=s.analyses?.at(-1);return '<div class="item"><div class="row spread"><div><b>'+E(s.title)+'</b><div class="small">'+fmt(s.updatedAt)+' · '+E(s.tags||'')+' · 시도 '+(s.attempts?.length||0)+'회</div><div class="small">최근 막힘: '+E(a?.first_block||'분석 전')+'</div></div><div class="row"><button class="btn" data-open="'+s.id+'">열기</button><button class="btn danger" data-del="'+s.id+'">삭제</button></div></div></div>'}).join(''):'아직 기록이 없습니다.')+'</section>'}
function mean(vals){return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0}
async function dashboardView(){const ss=await allSessions(),recent=ss.slice(0,12),latest=recent.map(s=>s.analyses?.at(-1)).filter(Boolean),av={};Object.keys(SKILLS).forEach(k=>av[k]=mean(latest.map(a=>Number(a.killer_feedback?.scores?.[k]||0))));const habits={};latest.forEach(a=>(a.killer_feedback?.habits||[]).forEach(h=>habits[h.name]=(habits[h.name]||0)+1));const top=Object.entries(habits).sort((a,b)=>b[1]-a[1]).slice(0,5);let trend='';if(recent.length>=4){const half=Math.floor(recent.length/2),newer=recent.slice(0,half).map(s=>s.analyses?.at(-1)).filter(Boolean),older=recent.slice(half).map(s=>s.analyses?.at(-1)).filter(Boolean),n=mean(newer.flatMap(a=>Object.values(a.killer_feedback?.scores||{}).map(Number))),o=mean(older.flatMap(a=>Object.values(a.killer_feedback?.scores||{}).map(Number)));trend=(n-o)>=.25?'최근 상승 중':(n-o)<=-.25?'최근 하락/정체 점검 필요':'최근 큰 변화 없음'}return '<h1>킬러 역량 추적</h1><section class="panel"><div class="grid3"><div><div class="small">기록 문제</div><div class="kpi">'+ss.length+'</div></div><div><div class="small">최근 평균 역량</div><div class="kpi">'+mean(Object.values(av)).toFixed(1)+'/5</div></div><div><div class="small">추세</div><div class="kpi" style="font-size:20px">'+E(trend||'기록 축적 필요')+'</div></div></div></section><section class="panel"><h2>최근 12문제 역량 평균</h2>'+skillRows(av)+'</section><section class="panel"><h2>반복되는 습관</h2>'+(top.length?top.map(([n,c])=>'<div class="habit"><b>'+E(n)+'</b> · 최근 '+c+'회 관찰</div>').join(''):'<p class="muted">아직 반복 습관을 판단할 기록이 부족합니다.</p>')+'<p class="small">한두 번의 실수보다 여러 문제에서 반복되는 패턴을 우선 교정 대상으로 봅니다.</p></section>'}
async function settingsView(){const h=await health();return '<h1>설정</h1><section class="panel"><h2>AI 연결</h2><p>'+(h.aiConfigured?'<span class="good"><b>연결됨</b></span>':'<span class="bad"><b>연결 안 됨</b></span>')+'</p><p class="small">모델: '+E(h.model||'-')+'</p></section><section class="panel"><h2>기록 백업</h2><div class="actions"><button class="btn" id="export">전체 기록 내보내기</button><label class="btn">기록 불러오기<input id="import" type="file" accept="application/json" class="hidden"></label><button class="btn danger" id="logout">로그아웃</button></div></section>'}
async function exportAll(){const ss=await allSessions(),blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),sessions:ss},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='killer-lab-records-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
async function importAll(file){const j=JSON.parse(await file.text());for(const s of (j.sessions||[]))await putSession(s);toast('기록을 불러왔습니다.');view='history';render()}
async function render(){setNav();if(!token){$('#app').innerHTML=loginView();return}let html='';if(view==='new')html=newView();else if(view==='history')html=await historyView();else if(view==='dashboard')html=await dashboardView();else if(view==='settings')html=await settingsView();else if(view==='session')html=await sessionView();$('#app').innerHTML=html}
document.addEventListener('change',async e=>{if(e.target.id==='problemFiles'){pendingProblem=await filesToData(e.target.files);render()}if(e.target.id==='attemptFiles'){pendingAttempt=await filesToData(e.target.files);render()}if(e.target.id==='retryFiles'){pendingAttempt=await filesToData(e.target.files);$('#retryPreview').innerHTML=imgs(pendingAttempt)}if(e.target.id==='import'&&e.target.files[0]){try{await importAll(e.target.files[0])}catch{toast('기록 파일을 읽지 못했습니다.')}}});
document.addEventListener('click',async e=>{const t=e.target.closest('button');if(!t)return;if(t.dataset.view){view=t.dataset.view;current=null;render();return}if(t.id==='login')return doLogin();if(t.id==='analyzeNew')return analyzeNew();if(t.id==='retryAnalyze')return retryAnalyze(false);if(t.id==='strongerHint')return retryAnalyze(true);if(t.id==='backHistory'){view='history';current=null;return render()}if(t.dataset.open){current=await getSession(t.dataset.open);view='session';return render()}if(t.dataset.del&&confirm('이 기록을 삭제할까요?')){await delSession(t.dataset.del);return render()}if(t.id==='export')return exportAll();if(t.id==='logout'){token='';localStorage.removeItem(API_TOKEN_KEY);return render()}});
document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.id==='pw')doLogin()});
render();